apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: simple-flask-app
spec: 
  selector: 
    matchLabels: 
      app: simple-flask-app
  replicas: 1 
  template: 
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
      - name: simple-flask-app
        image: simple-flask-app:1.0
        imagePullPolicy: Never
        ports: 
        - containerPort: 80
